### ISSUE TITLE
Display "number of images left to tag"

### ISSUE THREAD

**Issue by dbuscombe-usgs** [2320sharon/Sniffer#1]
I like how there is a text display that increments to tell me how many images I have tagged. But I'd also like to know how many images I have left to do. The principal reason is because eventually I'd like there to be an optional button that would initiate model training to autocomplete the classification process. Without a "X images remaining" display, a user wouldn't easily gauge when to stop tagging and start model training and implementation

this is like "human in the loop" for binary (yes/no type) image classification.

**Comment by 2320sharon** [comment]
I can make a progress bar next to the text that displays the current image index out of the total number of images.
